## PyTorch Tutorial

IFT6135 – Representation Learning

A Deep Learning Course, January 2019

By Chin-Wei Huang 

(Adapted from Sandeep Subramanian's MILA welcome tutorial)

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [1]:
import numpy as np
from __future__ import print_function

In [2]:
import torch

### Initialize a random tensor

In [3]:
torch.Tensor(5, 3)

tensor([[ 0.0000e+00, -1.5846e+29,  1.2648e+30],
        [-4.6577e-10,  9.8091e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.8167e-36,  1.4013e-45],
        [ 1.4013e-45,  1.4013e-45,  0.0000e+00]])

### From a uniform distribution

In [7]:
# intialization
print(torch.Tensor(5, 3).uniform_(-1, 1))
# sampling
print(torch.rand(5,3)*2-1)

tensor([[-0.8009,  0.5040,  0.1534],
        [ 0.5600,  0.5908,  0.6128],
        [ 0.9355, -0.0888, -0.0967],
        [ 0.0137, -0.2659,  0.1849],
        [-0.1018,  0.4046,  0.6622]])
tensor([[-0.9577,  0.0755, -0.9721],
        [-0.2880, -0.8543, -0.9403],
        [-0.9231,  0.2749, -0.4742],
        [-0.7808,  0.9098, -0.2767],
        [ 0.3118, -0.3696,  0.1999]])


### Get it's shape

In [21]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

# or your favorite np_array.shape
print(x.shape)

# dimensionality of the 0'th axis?
# print(???)

torch.Size([5, 3])
torch.Size([5, 3])


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |Tensor|
|----------|------|
|32-bit floating point|	torch.FloatTensor|
|64-bit floating point|	torch.DoubleTensor|
|16-bit floating point|	torch.HalfTensor|
|8-bit integer (unsigned)|torch.ByteTensor|
|8-bit integer (signed)|torch.CharTensor|
|16-bit integer (signed)|torch.ShortTensor|
|32-bit integer (signed)|torch.IntTensor|
|64-bit integer (signed)|torch.LongTensor|

### Creation from lists & numpy

In [22]:
z = torch.LongTensor([[1, 3], [2, 9]])
print(z.type())
# Cast to numpy ndarray
print(z.numpy().dtype)

torch.LongTensor
int64


In [23]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


In [24]:
# examples of type error
a = torch.randn(1) # x ~ N(0,1)
b = torch.from_numpy(np.ones(1))

# x+b

### Simple mathematical operations

In [25]:
y = x * torch.randn(5, 3)
print(y)

tensor([[ 0.1101, -0.0261,  0.1083],
        [-1.0404,  0.6263,  0.0480],
        [ 0.6126, -0.0869, -0.9221],
        [-1.0400,  0.1578, -0.0808],
        [ 0.7122,  0.0020, -0.1533]])


In [30]:
noise = torch.randn(5, 3)
y = x / torch.sqrt(noise ** 2)
# equal to torch.abs

print(y)


tensor([[ 0.2838,  0.4611, -0.1417],
        [-0.2973,  0.7785,  0.5817],
        [-0.5421, -0.9583,  0.2067],
        [ 1.1128, -1.9531,  3.9510],
        [ 0.9134,  0.0061, -3.3608]])


### Broadcasting

In [40]:
print(x.size())
print(x)
y = x + torch.ones(5, 1)
print(y)
# print(x + torch.arange(5))

torch.Size([5, 3])
tensor([[ 0.4557,  0.3413, -0.3695],
        [-0.3426,  0.8451,  0.9206],
        [-0.6317, -0.4046,  0.3733],
        [ 0.7993, -0.2102,  0.3512],
        [ 0.6476,  0.0046, -0.4898]])
tensor([[ 1.4557,  1.3413,  0.6305],
        [ 0.6574,  1.8451,  1.9206],
        [ 0.3683,  0.5954,  1.3733],
        [ 1.7993,  0.7898,  1.3512],
        [ 1.6476,  1.0046,  0.5102]])


### Reshape

In [45]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
#print(y.view(-1, 15).unsqueeze(1).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD)(Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)(AxBxCxD)
print()
#print(y.transpose(0, 1).size())
#print(y.transpose(1, 2).size())
#print(y.transpose(0, 1).transpose(1, 2).size())
#print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])



### Repeat

In [52]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())
# don't confuse it with tensor.repeat ...

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


### Concatenate

In [56]:
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

# Q: how to do tensor.stack using cat?

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])


### Advanced Indexing

In [61]:
y = torch.randn(2, 3, 4)
print(y[[1, 0, 1, 1]].size())

# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(rev_idx)
print(y[rev_idx].size())


# gather(input, dim, index)
# v = torch.arange(12).view(3,4)
# [0,1,2,3]
# [4,5,6,7]
# [8,9,10,11]
# want to return [1,6,8]


torch.Size([4, 3, 4])
tensor([ 1,  0])
torch.Size([2, 3, 4])


### GPU support

In [16]:
x = torch.cuda.HalfTensor(5, 3).uniform_(-1, 1)
y = torch.cuda.HalfTensor(3, 5).uniform_(-1, 1)
torch.matmul(x, y)


 0.2456  1.1543  0.5376  0.4358 -0.0369
 0.8247 -0.4143 -0.7188  0.3953  0.2573
-0.1346  0.7329  0.5156  0.0864 -0.1349
-0.3555  0.3135  0.3921 -0.1428 -0.1368
-0.4385  0.5601  0.6533 -0.2793 -0.5220
[torch.cuda.HalfTensor of size 5x5 (GPU 0)]

### Move tensors on the CPU -> GPU

In [17]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
x = x.cpu()
print(x)


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.FloatTensor of size 5x3]


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.FloatTensor of size 5x3]



### Contiguity in memory

In [18]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))


 0.4740 -0.9209  0.4143
-0.3473  0.4474 -0.8159
-0.7654 -0.0956  0.6145
-0.0846 -0.6239  0.8609
-0.8142  0.9289 -0.7020
[torch.FloatTensor of size 5x3]


 0.4740 -0.9209  0.4143
-0.3473  0.4474 -0.8159
-0.7654 -0.0956  0.6145
-0.0846 -0.6239  0.8609
-0.8142  0.9289 -0.7020
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]

Contiguity : True 
Contiguity : False 
Contiguity : True 
